use_frameworks!

platform :ios, '9.0'

target 'ZYFNetworking_Example' do
  pod 'ZYFNetworking', :path => '../'

  target 'ZYFNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
